import { useEffect, useState } from 'react'
import api, { getApiError } from '../api/api'

export default function DemandPage() {
  const [form,setForm]=useState({cropName:'',quantity:'',unit:'quintal',targetPrice:'',qualityRequirements:'',location:'',neededBy:'',notes:''})
  const [demands,setDemands]=useState([]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false)
  const update=k=>e=>setForm({...form,[k]:e.target.value})
  const load=async()=>{try{const {data}=await api.get('/demands/mine');setDemands(data)}catch(e){setError(getApiError(e,'Demands could not be loaded.'))}}
  useEffect(()=>{load()},[])
  const submit=async e=>{e.preventDefault();setLoading(true);setError('');setMessage('');try{await api.post('/demands',{...form,quantity:Number(form.quantity),targetPrice:form.targetPrice?Number(form.targetPrice):null});setMessage('Demand posted successfully.');setForm({...form,cropName:'',quantity:'',targetPrice:'',qualityRequirements:'',location:'',neededBy:'',notes:''});load()}catch(e){setError(getApiError(e,'Demand could not be posted.'))}finally{setLoading(false)}}
  const close=async id=>{try{await api.patch(`/demands/${id}/close`);load()}catch(e){setError(getApiError(e,'Could not close demand.'))}}
  return <div className="page-shell max-w-5xl"><p className="eyebrow">STEP 3 · BUYER DEMAND</p><h1 className="text-4xl font-display font-semibold mt-2">Post a buying requirement</h1><p className="text-ink-soft mt-2">Tell farmers the crop volume, target price and quality specifications you need.</p>{error&&<p className="text-red-600 mt-4">{error}</p>}{message&&<p className="text-forest mt-4">{message}</p>}<form onSubmit={submit} className="soft-card p-6 mt-6 grid md:grid-cols-2 gap-4"><label className="text-sm font-semibold">Crop name<input required className="field mt-1" value={form.cropName} onChange={update('cropName')}/></label><label className="text-sm font-semibold">Quantity<input required type="number" min="0.01" className="field mt-1" value={form.quantity} onChange={update('quantity')}/></label><label className="text-sm font-semibold">Unit<select className="field mt-1" value={form.unit} onChange={update('unit')}><option>quintal</option><option>kg</option><option>ton</option></select></label><label className="text-sm font-semibold">Target price<input type="number" min="0" className="field mt-1" value={form.targetPrice} onChange={update('targetPrice')}/></label><label className="text-sm font-semibold">Required location<input className="field mt-1" value={form.location} onChange={update('location')}/></label><label className="text-sm font-semibold">Needed by<input type="date" className="field mt-1" value={form.neededBy} onChange={update('neededBy')}/></label><label className="text-sm font-semibold md:col-span-2">Quality requirements<textarea className="field mt-1" placeholder="Grade, moisture, variety, packaging..." value={form.qualityRequirements} onChange={update('qualityRequirements')}/></label><label className="text-sm font-semibold md:col-span-2">Notes<textarea className="field mt-1" value={form.notes} onChange={update('notes')}/></label><button disabled={loading} className="btn-primary md:col-span-2">{loading?'Posting…':'Post demand'}</button></form><h2 className="text-2xl font-display font-semibold mt-10 mb-4">My demands</h2><div className="space-y-3">{demands.map(d=><div className="soft-card p-4 flex flex-col md:flex-row md:items-center justify-between gap-3" key={d._id}><div><b>{d.cropName}</b><p className="text-sm text-ink-soft">{d.quantity} {d.unit} · Target ₹{d.targetPrice||'—'} · {d.status}</p><p className="text-sm mt-1">Quality: {d.qualityRequirements||'Not specified'}</p></div>{d.status==='open'&&<button className="btn-secondary" onClick={()=>close(d._id)}>Close demand</button>}</div>)}</div>{!demands.length&&<p className="text-ink-soft">You have not posted any demand yet.</p>}</div>
}
