import {useCallback,useEffect,useState} from 'react'
import api,{getApiError} from '../api/api'
import {useAuth} from '../context/AuthContext'

export default function LogisticsPage(){
 const {user}=useAuth();const [orders,setOrders]=useState([]),[transporters,setTransporters]=useState([]),[bookings,setBookings]=useState([]),[form,setForm]=useState({}),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const load=useCallback(async()=>{try{const [o,t,b]=await Promise.all([api.get(`/orders/${user.role}`),api.get('/logistics/transporters'),api.get('/logistics/bookings/mine')]);setOrders(o.data||[]);setTransporters(t.data||[]);setBookings(b.data||[])}catch(e){setError(getApiError(e,'Logistics data could not be loaded.'))}},[user.role]);useEffect(()=>{load()},[load]);useEffect(()=>{const id=setInterval(load,15000);return()=>clearInterval(id)},[load]);
 const update=(k,v)=>setForm(s=>({...s,[k]:v}));
 const book=async()=>{if(!form.orderId||!form.pickupAddress||!form.deliveryAddress||!form.quantity){setError('Fill all required booking fields.');return}try{await api.post('/logistics/bookings',{orderId:form.orderId,transporterId:form.transporterId||null,pickupAddress:form.pickupAddress,deliveryAddress:form.deliveryAddress,quantity:Number(form.quantity)});setMsg('Logistics booking requested. Tracking refreshes every 15 seconds.');setForm({});load()}catch(e){setError(getApiError(e,'Booking failed.'))}}
 const advance=async(b,status)=>{try{await api.put(`/logistics/bookings/${b._id}/status`,{status,note:`Status updated by ${user.role}`});setMsg('Tracking status updated.');load()}catch(e){setError(getApiError(e,'Status update failed.'))}}
 return <div className="page-shell"><span className="eyebrow">LOGISTICS MODULE</span><h1 className="text-4xl font-display font-semibold mt-2">Book & track delivery</h1><p className="text-ink-soft mt-2">Create a transport request and follow its status. The page polls for updates every 15 seconds.</p>{error&&<div className="alert-error">{error}</div>}{msg&&<div className="alert-success">{msg}</div>}<div className="soft-card p-5 mt-7"><h2 className="font-display text-2xl font-semibold">New logistics booking</h2><div className="grid md:grid-cols-2 gap-4 mt-4"><select className="field" value={form.orderId||''} onChange={e=>update('orderId',e.target.value)}><option value="">Select order</option>{orders.map(o=><option key={o._id} value={o._id}>{o.crop?.name||'Crop'} · ₹{o.totalPrice} · {o._id.slice(-6)}</option>)}</select><select className="field" value={form.transporterId||''} onChange={e=>update('transporterId',e.target.value)}><option value="">Auto-select transporter</option>{transporters.map(t=><option key={t._id} value={t._id}>{t.name} · {t.vehicleType} · ₹{t.baseRatePerKm}/km</option>)}</select><input className="field" placeholder="Pickup address *" value={form.pickupAddress||''} onChange={e=>update('pickupAddress',e.target.value)}/><input className="field" placeholder="Delivery address *" value={form.deliveryAddress||''} onChange={e=>update('deliveryAddress',e.target.value)}/><input className="field" type="number" placeholder="Quantity *" value={form.quantity||''} onChange={e=>update('quantity',e.target.value)}/></div><button className="btn-primary mt-4" onClick={book}>Request booking</button></div><div className="space-y-4 mt-7">{bookings.map(b=><div className="soft-card p-5" key={b._id}><div className="flex flex-col md:flex-row md:justify-between gap-3"><div><h3 className="font-display text-xl font-semibold">Booking #{b._id.slice(-8)}</h3><p className="text-sm text-ink-soft mt-1">{b.pickupAddress} → {b.deliveryAddress}</p></div><span className="rounded-full bg-gold-soft px-3 py-1.5 text-xs font-semibold h-fit">{b.status}</span></div><div className="grid md:grid-cols-3 gap-3 mt-4 text-sm"><p><span className="text-ink-soft">Quantity</span><br/><b>{b.quantity}</b></p><p><span className="text-ink-soft">Latitude</span><br/><b>{b.tracking?.latitude??'—'}</b></p><p><span className="text-ink-soft">Longitude</span><br/><b>{b.tracking?.longitude??'—'}</b></p></div><p className="text-sm text-ink-soft mt-3">{b.tracking?.note||'No tracking note yet.'}</p><div className="flex flex-wrap gap-2 mt-4">{['confirmed','picked-up','in-transit','delivered'].map(s=><button key={s} className="btn-secondary text-xs" disabled={b.status===s||b.status==='delivered'} onClick={()=>advance(b,s)}>{s}</button>)}</div></div>)}{!bookings.length&&<div className="soft-card p-10 text-center">No logistics bookings yet.</div>}</div></div>
}
