import {useEffect,useState} from 'react'
import api,{getApiError} from '../api/api'
import {useAuth} from '../context/AuthContext'

export default function PaymentTrackingPage(){
 const {user}=useAuth();const [rows,setRows]=useState([]);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const {data}=await api.get(`/orders/${user.role}`);const list=await Promise.all((data||[]).map(async o=>{try{const r=await api.get(`/payments/order/${o._id}`);return {...o,payment:r.data}}catch{return {...o,payment:null}}}));setRows(list)}catch(e){setError(getApiError(e,'Payments could not be loaded.'))}})()},[user.role])
 return <div className="page-shell"><span className="eyebrow">PAYMENT TRACKING</span><h1 className="text-4xl font-display font-semibold mt-2">Payments</h1><p className="text-ink-soft mt-2">Track Razorpay payment status for every order.</p>{error&&<div className="alert-error">{error}</div>}<div className="space-y-4 mt-7">{rows.map(o=><div className="soft-card p-5" key={o._id}><div className="flex flex-col md:flex-row md:justify-between gap-3"><div><h3 className="font-display text-xl font-semibold">{o.crop?.name||'Crop'} · ₹{o.totalPrice}</h3><p className="text-sm text-ink-soft mt-1">Order: {o._id}</p></div><span className="rounded-full bg-gold-soft px-3 py-1.5 text-xs font-semibold h-fit">{o.payment?.status||'not initiated'}</span></div><div className="grid md:grid-cols-3 gap-3 mt-4 text-sm"><div><span className="text-ink-soft">Transaction ID</span><p className="font-semibold break-all">{o.payment?.transactionId||'—'}</p></div><div><span className="text-ink-soft">Amount</span><p className="font-semibold">₹{o.payment?.amount||o.totalPrice}</p></div><div><span className="text-ink-soft">Updated</span><p className="font-semibold">{o.payment?.updatedAt?new Date(o.payment.updatedAt).toLocaleString():'—'}</p></div></div></div>)}{!rows.length&&<div className="soft-card p-10 text-center">No orders/payment records found.</div>}</div></div>
}
