import {useCallback,useEffect,useState} from 'react'
import api,{getApiError} from '../api/api'
import {useAuth} from '../context/AuthContext'

export default function StoragePage(){
 const {user}=useAuth(); const [warehouses,setWarehouses]=useState([]),[orders,setOrders]=useState([]),[bookings,setBookings]=useState([]),[form,setForm]=useState({}),[error,setError]=useState(''),[msg,setMsg]=useState('')
 const load=useCallback(async()=>{try{const [w,b,o]=await Promise.all([api.get('/storage/warehouses'),api.get('/storage/bookings/mine'),api.get(`/orders/${user.role}`)]);setWarehouses(w.data||[]);setBookings(b.data||[]);setOrders(o.data||[])}catch(e){setError(getApiError(e,'Storage data could not be loaded.'))}},[user.role])
 useEffect(()=>{load()},[load])
 const update=(k,v)=>setForm(s=>({...s,[k]:v}))
 const book=async()=>{setError('');setMsg('');if(!form.warehouseId||!form.quantity||!form.startDate){setError('Select warehouse, quantity and start date.');return}try{await api.post('/storage/bookings',{warehouseId:form.warehouseId,orderId:form.orderId||null,quantity:Number(form.quantity),startDate:form.startDate,endDate:form.endDate||null,notes:form.notes||''});setMsg('Storage booking requested successfully.');setForm({});load()}catch(e){setError(getApiError(e,'Storage booking failed.'))}}
 const updateStatus=async(id,status)=>{try{await api.put(`/storage/bookings/${id}/status`,{status});load()}catch(e){setError(getApiError(e,'Status update failed.'))}}
 return <div className="page-shell"><span className="eyebrow">STORAGE MODULE</span><h1 className="text-4xl font-display font-semibold mt-2">Warehouse & storage booking</h1><p className="text-ink-soft mt-2">Reserve available capacity and track your storage requests.</p>{error&&<div className="alert-error">{error}</div>}{msg&&<div className="alert-success">{msg}</div>}
 <div className="soft-card p-5 mt-7"><h2 className="font-display text-2xl font-semibold">New storage booking</h2><div className="grid md:grid-cols-2 gap-4 mt-4"><select className="field" value={form.warehouseId||''} onChange={e=>update('warehouseId',e.target.value)}><option value="">Select warehouse</option>{warehouses.map(w=><option key={w._id} value={w._id}>{w.name} · {w.location} · {w.availableCapacity} {w.unit} available</option>)}</select><select className="field" value={form.orderId||''} onChange={e=>update('orderId',e.target.value)}><option value="">Optional order</option>{orders.map(o=><option key={o._id} value={o._id}>{o.crop?.name||'Crop'} · {o._id.slice(-6)}</option>)}</select><input className="field" type="number" placeholder="Quantity *" value={form.quantity||''} onChange={e=>update('quantity',e.target.value)}/><input className="field" type="date" value={form.startDate||''} onChange={e=>update('startDate',e.target.value)}/><input className="field" type="date" value={form.endDate||''} onChange={e=>update('endDate',e.target.value)}/><input className="field" placeholder="Notes" value={form.notes||''} onChange={e=>update('notes',e.target.value)}/></div><button className="btn-primary mt-4" onClick={book}>Request storage</button>{!warehouses.length&&<p className="text-sm text-ink-soft mt-3">No active warehouses are listed yet. An administrator must add warehouse records first.</p>}</div>
 <div className="space-y-4 mt-7">{bookings.map(b=><div className="soft-card p-5" key={b._id}><div className="flex justify-between gap-3"><div><h3 className="font-display text-xl font-semibold">{b.warehouseDetails?.name||'Warehouse booking'}</h3><p className="text-sm text-ink-soft">{b.warehouseDetails?.location||'Location unavailable'}</p></div><span className="rounded-full bg-gold-soft px-3 py-1.5 text-xs font-semibold h-fit">{b.status}</span></div><div className="grid md:grid-cols-3 gap-3 mt-4 text-sm"><p><span className="text-ink-soft">Quantity</span><br/><b>{b.quantity}</b></p><p><span className="text-ink-soft">Start date</span><br/><b>{b.startDate}</b></p><p><span className="text-ink-soft">End date</span><br/><b>{b.endDate||'—'}</b></p></div><div className="flex flex-wrap gap-2 mt-4">{['confirmed','stored','released','cancelled'].map(s=><button className="btn-secondary text-xs" key={s} disabled={b.status===s||b.status==='released'||b.status==='cancelled'} onClick={()=>updateStatus(b._id,s)}>{s}</button>)}</div></div>)}{!bookings.length&&<div className="soft-card p-10 text-center">No storage bookings yet.</div>}</div></div>
}
