import {useCallback,useEffect,useState} from 'react'
import api,{getApiError} from '../api/api'
import {useAuth} from '../context/AuthContext'

export default function TrustPage(){
 const {user}=useAuth();const [orders,setOrders]=useState([]),[ratings,setRatings]=useState([]),[disputes,setDisputes]=useState([]),[rating,setRating]=useState({}),[dispute,setDispute]=useState({}),[error,setError]=useState(''),[msg,setMsg]=useState('')
 const load=useCallback(async()=>{try{const [o,r,d]=await Promise.all([api.get(`/orders/${user.role}`),api.get('/ratings/mine'),api.get('/disputes/mine')]);setOrders(o.data||[]);setRatings(r.data||[]);setDisputes(d.data||[])}catch(e){setError(getApiError(e,'Trust data could not be loaded.'))}},[user.role]);useEffect(()=>{load()},[load])
 const rate=async()=>{try{await api.post(`/ratings/order/${rating.orderId}`,{score:Number(rating.score),comment:rating.comment||''});setMsg('Rating submitted.');setRating({});load()}catch(e){setError(getApiError(e,'Rating could not be submitted.'))}}
 const openDispute=async()=>{try{await api.post(`/disputes/order/${dispute.orderId}`,{reason:dispute.reason,details:dispute.details});setMsg('Dispute opened and sent for review.');setDispute({});load()}catch(e){setError(getApiError(e,'Dispute could not be opened.'))}}
 return <div className="page-shell"><span className="eyebrow">TRUST & SAFETY</span><h1 className="text-4xl font-display font-semibold mt-2">Ratings & dispute resolution</h1><p className="text-ink-soft mt-2">Rate completed transactions and raise an issue with order evidence.</p>{error&&<div className="alert-error">{error}</div>}{msg&&<div className="alert-success">{msg}</div>}
 <div className="grid md:grid-cols-2 gap-6 mt-7"><div className="soft-card p-5"><h2 className="font-display text-2xl font-semibold">Rate a delivered order</h2><select className="field mt-4" value={rating.orderId||''} onChange={e=>setRating(s=>({...s,orderId:e.target.value}))}><option value="">Select delivered order</option>{orders.filter(o=>o.status==='delivered').map(o=><option key={o._id} value={o._id}>{o.crop?.name||'Crop'} · {o._id.slice(-6)}</option>)}</select><select className="field mt-3" value={rating.score||''} onChange={e=>setRating(s=>({...s,score:e.target.value}))}><option value="">Rating</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select><textarea className="field mt-3" placeholder="Comment" value={rating.comment||''} onChange={e=>setRating(s=>({...s,comment:e.target.value}))}/><button className="btn-primary mt-3" onClick={rate} disabled={!rating.orderId||!rating.score}>Submit rating</button></div>
 <div className="soft-card p-5"><h2 className="font-display text-2xl font-semibold">Open a dispute</h2><select className="field mt-4" value={dispute.orderId||''} onChange={e=>setDispute(s=>({...s,orderId:e.target.value}))}><option value="">Select order</option>{orders.map(o=><option key={o._id} value={o._id}>{o.crop?.name||'Crop'} · {o._id.slice(-6)}</option>)}</select><input className="field mt-3" placeholder="Reason" value={dispute.reason||''} onChange={e=>setDispute(s=>({...s,reason:e.target.value}))}/><textarea className="field mt-3" placeholder="Describe the issue and evidence" value={dispute.details||''} onChange={e=>setDispute(s=>({...s,details:e.target.value}))}/><button className="btn-primary mt-3" onClick={openDispute} disabled={!dispute.orderId||!dispute.reason||!dispute.details}>Open dispute</button></div></div>
 <div className="soft-card p-5 mt-7"><h2 className="font-display text-2xl font-semibold">My disputes</h2><div className="space-y-3 mt-4">{disputes.map(d=><div className="rounded-xl border border-line p-4" key={d._id}><div className="flex justify-between gap-3"><b>{d.reason}</b><span className="text-xs rounded-full bg-gold-soft px-3 py-1">{d.status}</span></div><p className="text-sm text-ink-soft mt-2">{d.details}</p>{d.resolution&&<p className="text-sm mt-2"><b>Resolution:</b> {d.resolution}</p>}</div>)}{!disputes.length&&<p className="text-ink-soft">No disputes raised.</p>}</div></div>
 <div className="soft-card p-5 mt-7"><h2 className="font-display text-2xl font-semibold">Submitted ratings</h2><div className="space-y-3 mt-4">{ratings.map(r=><div className="rounded-xl border border-line p-4" key={r._id}><b>{r.score} / 5</b><p className="text-sm text-ink-soft mt-1">{r.comment||'No comment'}</p></div>)}{!ratings.length&&<p className="text-ink-soft">No ratings submitted yet.</p>}</div></div></div>
}
